### ISSUE TITLE
Symbol $ in --viserver-password

### ISSUE THREAD

**Issue by Igor-178** [kurokobo/virtualbmc-for-vsphere#19]
Environment:
CentOS Stream 8 
Python 3.6.8
vsbmc 0.3.0

I followed the documentation in installing the package, and start vbmcd.
Then I added a new virtual BMC to control VM called control-1-os-loc. The password for the viserver contains the characters '$'

`vsbmc add control-1-os-loc --port 6230 --viserver 10.169.173.3 --viserver-username administrator@vsphere.local --viserver-password Pa$$word1`

As a result, a different password is stored in the settings configuration file, and virtual machine management does not work.

`[root@vbmc ~]# cat .vsbmc/control-1-os-loc/config`
[VirtualBMC]
vm_name = control-1-os-loc
username = admin
password = password
port = 6230
address = ::
fakemac = 02:00:00:0f:e1:50
viserver = 10.169.173.3
viserver_username = administrator@vsphere.local
viserver_password = **Pa3248word1**
active = False

**Comment by kurokobo** [comment]
@Igor-178 
The double dollar (`$$`) in Bash returns its PID.

```bash
$ echo $$
1066852
```

If you want to use `$` as plain text in your command, wrap your string with single quote. I mean, you should invoke this:

```bash
vsbmc add control-1-os-loc --port 6230 --viserver 10.169.173.3 --viserver-username administrator@vsphere.local --viserver-password 'Pa$$word1'
```

**Comment by Igor-178** [comment]
Okay, thanks for your advice. This solved the problem.
